services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis
    ports:
      - "6379:6379"

  chatbot:
    image: chatbot
    container_name: chatbot
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - .env
    command: ["/bin/bash", "entrypoint.sh"]
    ports:
      - "8080:8080"
    depends_on:
      - redis